### ISSUE TITLE
get_pid fails on windows

### ISSUE THREAD

**Issue by mteam88** [crowdcores/crowdcores_node#1]
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python311\Scripts\crowdcores-node.exe__main.py", line 7, in <module>
  File "C:\Python311\Lib\site-packages\crowdcores_node\manager.py", line 94, in main
    start()
  File "C:\Python311\Lib\site-packages\crowdcores_node\manager.py", line 12, in start
    pid = get_pid()
          ^^^^^^^^^
  File "C:\Python311\Lib\site-packages\crowdcores_node\manager.py", line 71, in get_pid
    process = subprocess.Popen(["pgrep", "-f", "crowdcores_node.py"], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\subprocess.py", line 1024, in init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Python311\Lib\subprocess.py", line 1509, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

Looks like we need to add an alternate implementation of get_pid or similar for windows.  Overall the method of checking if a node is running can be modified to improve robustness, but right now a quick fix should work.

**Comment by mteam88** [comment]
Seems to still be an issue, something abt permissions.
